/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(public)'
    >,
    '//(public)': RouteRecordInfo<
      '//(public)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/(adminacceuil)'
    >,
    '/admin/(adminacceuil)': RouteRecordInfo<
      '/admin/(adminacceuil)',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app': RouteRecordInfo<
      '/app',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | '/app/(acceuilapp)'
      | '/app/menu/cookableMenu'
      | '/app/pantry_staple/(pantry_staple)'
      | '/app/recipes/[id]'
      | '/app/recipes/recipesList'
      | '/app/stock/StockView'
    >,
    '/app/(acceuilapp)': RouteRecordInfo<
      '/app/(acceuilapp)',
      '/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/menu/cookableMenu': RouteRecordInfo<
      '/app/menu/cookableMenu',
      '/app/menu/cookableMenu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/pantry_staple/(pantry_staple)': RouteRecordInfo<
      '/app/pantry_staple/(pantry_staple)',
      '/app/pantry_staple',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/recipes/[id]': RouteRecordInfo<
      '/app/recipes/[id]',
      '/app/recipes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/app/recipes/recipesList': RouteRecordInfo<
      '/app/recipes/recipesList',
      '/app/recipes/recipesList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/stock/StockView': RouteRecordInfo<
      '/app/stock/StockView',
      '/app/stock/StockView',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(public)'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(public).vue': {
      routes:
        | '//(public)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/(adminacceuil)'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/admin/(adminacceuil).vue': {
      routes:
        | '/admin/(adminacceuil)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app.vue': {
      routes:
        | '/app'
        | '/app/(acceuilapp)'
        | '/app/menu/cookableMenu'
        | '/app/pantry_staple/(pantry_staple)'
        | '/app/recipes/[id]'
        | '/app/recipes/recipesList'
        | '/app/stock/StockView'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/app/(acceuilapp).vue': {
      routes:
        | '/app/(acceuilapp)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/menu/cookableMenu.vue': {
      routes:
        | '/app/menu/cookableMenu'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/pantry_staple/(pantry_staple).vue': {
      routes:
        | '/app/pantry_staple/(pantry_staple)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/recipes/[id].vue': {
      routes:
        | '/app/recipes/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/app/recipes/recipesList.vue': {
      routes:
        | '/app/recipes/recipesList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/stock/StockView.vue': {
      routes:
        | '/app/stock/StockView'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
